build site:
  image: node:6
  stage: build
  before_script:
    - bash prepare_ci.sh > /dev/null
  script:
    - npm install --progress=false
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules

deploy:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav -e 'ssh -p 2424' --delete build/ ndo@94.249.131.5:/opt/vaca_prod
